### ISSUE TITLE
Validate service dependency constraints during connector load

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/simple-data-pipe#17]
Currently connectors have to explicitly validate that additional required services are bound to the Simple Data Pipe application. The task should be performed by the SDP framework.

**Comment by ptitzler** [comment]
@DTAIEB: Suggesting to extend _package.json_ metadata to include 

````
 "simple-data-pipe" :
    {
      "name": "<connector_name>",
      "service_dependencies" : [
                                {
                                  "service_name"  : "<bluemix_service_name>",
                                  "service_plan"  : "<bluemix_service_plan_name>",
                                  "instance_name" : "<bluemix_service_instance_name>"                               
                                }
                               ]
    }
````
Property description:

- name*: connector name [mandatory]
- service_dependencies:  [optional]
 - service_name:  Bluemix service name [mandatory]
 - service_plan:  Bluemix service plan name [mandatory]
 - instance_plan:  Bluemix service instance name  [mandatory]

The Simple Data Pipe framework will not load a connector unless the stated services are bound.

> The current property `"pipes-connector-name": "<connector_name>"` will be deprecated.

**Comment by DTAIEB** [comment]
Looks good to me. Perhaps we should investigate how hard it would be to automatically add these services from pipes (don't think it's possible via REST Apis today though).
Also, what type of explanatory error message are we planning to give the user when dependencies fail to resolve?

**Comment by ptitzler** [comment]
> automatically add ...

Yes, exactly.
> error message ...

If it is detected that a connector cannot be loaded (e.g. because a service is not bound), the Web console would display on the connector status page something like this:

|  Connector | status | home page |
|  ----- | ----- | -----  |
|  reddit | disabled (service missing) | https://www.github.com/... |
|  salesforce | enabled| https://www.github.com/... |

Connectors that can't be loaded (for whatever reason) would not be displayed (or can't be selected  in the new data pipe pipe wizard).

**Comment by DTAIEB** [comment]
+1

**Comment by ptitzler** [comment]
@DTAIEB, just realized we'd probably have more processing flexibility if the top-level property was named "simple_data_pipe" instead of "simple-data-pipe".

**Comment by DTAIEB** [comment]
@ptitzler just curious, can you explain why more flexibility?

**Comment by ptitzler** [comment]
Let's say we want to traverse down the application-specific properties tree to inspect certain values, we couldn't simple turn `simple-data-pipe` into a variable to go after them. For example `if(! simple-data-pipe.service_dependencies)`wouldn't work.

**Comment by DTAIEB** [comment]
I see, we would have to use the ["simple-data-pipe"] notation which is cumbersome. Let's change it now then

**Comment by ptitzler** [comment]
I just realized that we also need to add an optional service property to support detection of service instances that don't follow the default naming scheme, as it is done today by the connectors:

`vcapServices.getService( configManager.get("WATSON_TONE_ANALYZER") || "tone analyzer" )`

The service definition would look as follows:

```json
 "simple_data_pipe" :
    {
      "name": "<connector_name>",
      "service_dependencies" : [
                                {
                                  "service_name"  : "<bluemix_service_name>",
                                  "service_plan"  : "<bluemix_service_plan_name>",
                                  "instance_name" : "<bluemix_service_instance_name>",
                                  "vcap_env_service_alias" : "<bluemix_app_env_var_name>"                               
                                }
                               ]
    }
```

Example definition in connector's `package.json`:

```json
 "simple_data_pipe" :
    {
      "name": "reddit",
      "service_dependencies" : [
                                {
                                  "service_name"  : "tone_analyzer",
                                  "service_plan"  : "experimental",
                                  "instance_name" : "tone analyzer",
                                  "vcap_env_service_alias" : "WATSON_TONE_ANALYZER"                               
                                }
                               ]
    } 
```

**Comment by ptitzler** [comment]
Validation logic is as follows:
 - `service_dependencies` property is not defined - no validation (connector is loaded)
 - `service_dependencies` property is empty array - no validation (connector is loaded)
 - `service_dependencies` value is missing `service_name`, `service_plan` or `instance_name` property - error logged and connector is not loaded (to support a future scenario in which services could be provisioned on the fly)
 - `service_dependencies` entry includes property `vcap_env_service_alias` - service validation is performed using `vcapServices.getService(  <bluemix_service_instance_name> )` and connector is only loaded if all prerequisites services are bound
 - `service_dependencies` entry includes `vcap_env_service_alias` - service validation is performed using `vcapServices.getService( configManager.get(<bluemix_app_env_var_name>) || <bluemix_service_instance_name> )` and connector is only loaded if all prerequisites services are bound

**Comment by ptitzler** [comment]
Delivered by #31
