### ISSUE TITLE
Sort activity chronologically by date & time

### ISSUE THREAD

**Issue by mikebroberg** [ibm-cds-labs/simple-data-pipe#32]
Future request. Right now details on previous pipe runs appear in random order. This has been the case with the old UI and is still in the new UI. Thanks.

**Comment by vabarbosa** [comment]
[commit 9445356](https://github.com/ibm-cds-labs/simple-data-pipe/commit/9445356db060ec64bb30212be5ec8f4cb561df56) should resolve the progress bar issue and this request
